# Base Configuration for maXTouch Test Shield

# Enable Pointing & Input
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_I2C=y

# Enable Microchip maXTouch Driver
CONFIG_INPUT_MICROCHIP_MAXTOUCH=y

# Disable ZMK External Power driver (leaves P0.13 untouched at hardware 3.3V default)
CONFIG_ZMK_EXT_POWER=n

# Enable USB CDC ACM Serial Console for Debug Logging
CONFIG_USB_DEVICE_STACK=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_ZMK_USB_LOGGING=y
CONFIG_INPUT_LOG_LEVEL_DBG=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000
