# Base Configuration for maXTouch Test Shield

# Enable ZMK Pointing Subsystem
CONFIG_ZMK_POINTING=y

# Enable Microchip maXTouch Driver
CONFIG_INPUT_MICROCHIP_MAXTOUCH=y

# Enable USB Debug Logging over Serial Console
CONFIG_ZMK_USB_LOGGING=y
CONFIG_INPUT_LOG_LEVEL_DBG=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000
